### ISSUE TITLE
More functionalities related to cart state management

### ISSUE THREAD

**Issue by Ruslanbek0809** [mo7amedaliEbaid/piiicks-ecommerce#9]
Hi,
Thank you for providing this project as an open-source for us to use. Do you use this cart state management in your product apps as well? Asking this to know whether it is a good approach for the production app. 
Also, can you do us a favor and provide a code snippet for implementing quantity update functionality and its synch with local storage (in this case it is shared pref)?

**Comment by mo7amedaliEbaid** [comment]
What do you mean by cart state management?
And for the second part of your question,  the api that I use doesn't have a service / endpoint to update quantity.

**Comment by Ruslanbek0809** [comment]
Cart state management means shopping cart in short which includes adding, incrementing, decrementing, removing, etc.
Would be great if you include the updating as well.
